# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ssacChatting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ssacChatting
pod 'Socket.IO-Client-Swift', '~> 15.2.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire', '~> 5.5'
end
